print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill? $"))
total_people = int(input("How many people to split the bill? "))
tip_percentage = int(input("What percentage tip would you like to give? 10,12, or 15? "))
tip_amount = round((total_bill/total_people)*(1 +(tip_percentage/100)), 2)
print(f"Each person should pay: ${tip_amount}")